### ISSUE TITLE
autocompletion doesn't works inside class or function

### ISSUE THREAD

**Issue by dashingspidy** [gerardroche/sublime-phpck#10]
Greetings,

Auto complete doesn't works inside a class or function. it works directly under `<?php` tag only.
Screenshot: 
**Inside a** `class`
![screen shot 2016-08-16 at 01 05 21](https://cloud.githubusercontent.com/assets/4521441/17682708/b4a62c9e-634d-11e6-89d1-9be39187e92c.png)

**Outside of** `class`
![screen shot 2016-08-16 at 01 06 15](https://cloud.githubusercontent.com/assets/4521441/17682709/b4a66376-634d-11e6-926a-4df562ef5f6c.png)

**Comment by gerardroche** [comment]
The default PHP syntax made changes that broke some things.

The quickest solution is to install my php-grammar package. I use this package so it will always work correctly with my other packages like PHP Completions Kit.

**Comment by gerardroche** [comment]
# Notes

The default package changed the scope inside class to:

```
embedding.php text.html.basic meta.embedded.block.php source.php meta.class.php meta.block.php meta.function.php meta.block.php
```

Previous scope and the scope in php-grammar is:

```
embedding.php text.html.basic meta.embedded.block.php source.php
```

The completions kit scope for functions completions is:

```
embedding.php text.html.basic meta.embedded.block.php source.php meta.class.php meta.block.php meta.function.php meta.block.php
```

Looks like there's no way to make completions kit  compatible with both the default package and php-grammar.

**Comment by dashingspidy** [comment]
Great! Problem solved.

**Comment by joacub** [comment]
for not work inner function whats is the solutions in sublime text 3

**Comment by gerardroche** [comment]
@joacub The quickest solution is to install my [php-grammar](https://packagecontrol.io/browse/authors/gerardroche) package. I use this package so it will always work correctly with my other packages like PHP Completions Kit.
