### ISSUE TITLE
Add argument types and defaults to completions

### ISSUE THREAD

**Issue by FeBe95** [gerardroche/sublime-phpck#14]
It would be really nice to have the allowed argument types and default values added to the definitions like so:
```
// before
json_encode(value, options, depth)

// after
json_encode(mixed¦value, int¦options¦0, int¦depth¦512)
```

Its `.sublime-completion` definition would look like this:
```
// before
{"trigger":"json_encode","contents":"json_encode(${1:value}${2:, ${3:options}${4:, ${5:depth}}})"},

//after
{"trigger":"json_encode","contents":"json_encode(${1:mixed¦value}${2:, ${3:int¦options¦0}${4:, ${5:int¦depth¦512}}})"},
```

I don't know where you scrape the definitions but php.net already includes all required details:
e.g.: http://php.net/manual/de/function.json-encode.php

P.S.: I chose the Unicode "Broken Bar" `¦` so we are still able to double-click the arguments in order to select them entirely

**Comment by gerardroche** [comment]
I use PHP Reflection to automatically generate the completions. Types are not available through reflection for the built-in functions. It's a pity, I'd like the type details too.

**Comment by FeBe95** [comment]
Well, you're right about that :)

I just found this resource:
http://doc.php.net/downloads/json/php_manual_en.json
Is there something missing - compared to the details you get via PHP reflections?
This JSON file seems quite organized and it lists the desired info for every function in their prototype attribute!

**Comment by FeBe95** [comment]
Also, there's PHP's official GitHub repo, where even more info can be found:
https://github.com/php/php-src/blob/master/ext/standard/basic_functions.stub.php
